name:                frontend-haskell
version:             0.1.0.0
github:              "githubuser/frontend-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/frontend-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  dependencies:
  - wai
  - http-types
  - lucid
  - clay
  - sunroof-compiler
  - data-default-class
  - text
  - casing

executables:
  frontend-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frontend-haskell
    - warp
    - wai-extra
    - async
    - directory
    - foreign-store

tests:
  frontend-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frontend-haskell
